#!/usr/bin/env python3
"""Fail fast when a future Jimmy PAIge analyzer regresses below V71."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def load_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as file:
        return json.load(file)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--report",
        default="/tmp/jimmy-report.json",
        help="Benchmark report generated by modal_analyzer_benchmark.py",
    )
    parser.add_argument(
        "--baseline",
        default="analyzer/baselines/stairway_v71_green.json",
        help="Frozen green baseline JSON",
    )
    args = parser.parse_args()

    report = load_json(Path(args.report))
    baseline = load_json(Path(args.baseline))

    checks = [
        (
            "benchmarkScore",
            float(report.get("benchmarkScore") or 0.0)
            >= float(baseline["benchmarkScore"]),
            report.get("benchmarkScore"),
            f">= {baseline['benchmarkScore']}",
        ),
        (
            "positionZoneAccuracy",
            float(report.get("positionZoneAccuracy") or 0.0)
            >= float(baseline["positionZoneAccuracy"]),
            report.get("positionZoneAccuracy"),
            f">= {baseline['positionZoneAccuracy']}",
        ),
        (
            "canonicalSegmentCount",
            int(report.get("canonicalSegmentCount") or 0)
            >= int(baseline["canonicalSegmentCount"]),
            report.get("canonicalSegmentCount"),
            f">= {baseline['canonicalSegmentCount']}",
        ),
        (
            "largeUpperPositionShifts",
            int(report.get("largeUpperPositionShifts") or 0)
            >= int(baseline["largeUpperPositionShifts"]),
            report.get("largeUpperPositionShifts"),
            f">= {baseline['largeUpperPositionShifts']}",
        ),
        (
            "unnecessaryOpenCollapses",
            int(report.get("unnecessaryOpenCollapses") or 0)
            <= int(baseline["unnecessaryOpenCollapses"]),
            report.get("unnecessaryOpenCollapses"),
            f"<= {baseline['unnecessaryOpenCollapses']}",
        ),
        (
            "highPositionOvercorrections",
            int(report.get("highPositionOvercorrections") or 0)
            <= int(baseline["highPositionOvercorrections"]),
            report.get("highPositionOvercorrections"),
            f"<= {baseline['highPositionOvercorrections']}",
        ),
        (
            "lowPositionUndercorrections",
            int(report.get("lowPositionUndercorrections") or 0)
            <= int(baseline["lowPositionUndercorrections"]),
            report.get("lowPositionUndercorrections"),
            f"<= {baseline['lowPositionUndercorrections']}",
        ),
    ]

    failed = False
    print("JIMMY PAIGE STAIRWAY REGRESSION GUARD")
    print("=" * 48)
    print("Engine:", report.get("engineVersion"))

    for name, passed, actual, expected in checks:
        marker = "PASS" if passed else "FAIL"
        print(f"{marker:4}  {name}: {actual}  expected {expected}")
        failed = failed or not passed

    if failed:
        raise SystemExit("\nRegression detected. Do not deploy this analyzer.")

    print("\nGREEN BASELINE PRESERVED 💚")


if __name__ == "__main__":
    main()
