#!/usr/bin/env python3
"""Fail fast when a future Jimmy PAIge analyzer regresses below the green bend baseline."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def load_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as file:
        return json.load(file)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--report",
        default="/tmp/gomyway-notation-report.json",
        help="Report generated by modal_bend_notation_handoff_benchmark_v2.py",
    )
    parser.add_argument(
        "--baseline",
        default="analyzer/baselines/gomyway_bends_green.json",
        help="Frozen Go My Way bend baseline JSON",
    )
    args = parser.parse_args()

    report = load_json(Path(args.report))
    baseline = load_json(Path(args.baseline))

    expected_count = int(baseline["expectedBendCount"])
    required = baseline["requiredTechnique"]
    required_ids = set(baseline["requiredBendIds"])
    annotations = [
        item for item in report.get("annotations", []) if isinstance(item, dict)
    ]
    annotation_ids = {str(item.get("bendId")) for item in annotations}

    checks = [
        (
            "protectedAnalyzer",
            report.get("protectedAnalyzer") == baseline["protectedAnalyzer"],
            report.get("protectedAnalyzer"),
            baseline["protectedAnalyzer"],
        ),
        (
            "expectedBendCount",
            int(report.get("expectedBendCount") or 0) == expected_count,
            report.get("expectedBendCount"),
            expected_count,
        ),
        (
            "continuousEvidenceCount",
            int(report.get("continuousEvidenceCount") or 0)
            >= int(baseline["continuousEvidenceCount"]),
            report.get("continuousEvidenceCount"),
            f">= {baseline['continuousEvidenceCount']}",
        ),
        (
            "notationReadyCount",
            int(report.get("notationReadyCount") or 0)
            >= int(baseline["notationReadyCount"]),
            report.get("notationReadyCount"),
            f">= {baseline['notationReadyCount']}",
        ),
        (
            "notationAccuracy",
            float(report.get("notationAccuracy") or 0.0)
            >= float(baseline["notationAccuracy"]),
            report.get("notationAccuracy"),
            f">= {baseline['notationAccuracy']}",
        ),
        (
            "syntheticSourceAnchorCount",
            int(report.get("syntheticSourceAnchorCount") or 0)
            <= int(baseline["syntheticSourceAnchorCount"]),
            report.get("syntheticSourceAnchorCount"),
            f"<= {baseline['syntheticSourceAnchorCount']}",
        ),
        (
            "passed",
            bool(report.get("passed")),
            report.get("passed"),
            True,
        ),
        (
            "requiredBendIds",
            required_ids.issubset(annotation_ids),
            sorted(annotation_ids),
            sorted(required_ids),
        ),
    ]

    for bend_id in sorted(required_ids):
        item = next(
            (entry for entry in annotations if entry.get("bendId") == bend_id),
            None,
        )
        technique_ok = bool(
            item
            and item.get("notationReady")
            and int(item.get("stringIndex") or -1) == int(required["stringIndex"])
            and int(item.get("fret") or -1) == int(required["fret"])
            and int(item.get("amountSemitones") or 0)
            == int(required["amountSemitones"])
            and bool(item.get("release")) is bool(required["release"])
        )
        actual = None
        if item:
            fret = int(item.get("fret") or 0)
            amount = int(item.get("amountSemitones") or 0)
            actual = {
                "stringIndex": item.get("stringIndex"),
                "fret": item.get("fret"),
                "amountSemitones": item.get("amountSemitones"),
                "release": item.get("release"),
                "notationReady": item.get("notationReady"),
                "notation": f"{fret}b{fret + amount}r{fret}",
            }
        checks.append((bend_id, technique_ok, actual, required))

    failed = False
    print("JIMMY PAIGE GO MY WAY BEND REGRESSION GUARD")
    print("=" * 52)
    print("Protected analyzer:", report.get("protectedAnalyzer"))

    for name, passed, actual, expected in checks:
        marker = "PASS" if passed else "FAIL"
        print(f"{marker:4}  {name}: {actual}  expected {expected}")
        failed = failed or not passed

    if failed:
        raise SystemExit("\nBend regression detected. Do not deploy this analyzer.")

    print("\nGO MY WAY BEND BASELINE PRESERVED 💚")


if __name__ == "__main__":
    main()
