#!/usr/bin/env python3
"""Fail fast when the Go My Way chorus chord/sustain benchmark regresses."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def load_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as file:
        return json.load(file)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--report",
        default="/tmp/gomyway-chorus-chord-sustain-v6-report.json",
        help="Report generated by modal_gomyway_chorus_chord_sustain_benchmark_v6.py",
    )
    parser.add_argument(
        "--baseline",
        default="analyzer/baselines/gomyway_chorus_chord_sustain_v6_green.json",
        help="Frozen chorus chord/sustain V6 green baseline JSON",
    )
    args = parser.parse_args()

    report = load_json(Path(args.report))
    baseline = load_json(Path(args.baseline))
    checks_map = report.get("checks") or {}
    vocabulary = set(str(value) for value in (report.get("chordVocabulary") or []))
    repeated = report.get("repeatedAttackCounts") or {}

    checks: list[tuple[str, bool, Any, Any]] = [
        (
            "benchmarkVersion",
            int(report.get("benchmarkVersion") or 0) == int(baseline["benchmarkVersion"]),
            report.get("benchmarkVersion"),
            baseline["benchmarkVersion"],
        ),
        (
            "benchmarkType",
            report.get("benchmarkType") == baseline["benchmarkType"],
            report.get("benchmarkType"),
            baseline["benchmarkType"],
        ),
        (
            "analysisPath",
            report.get("analysisPath") == baseline["analysisPath"],
            report.get("analysisPath"),
            baseline["analysisPath"],
        ),
        ("passed", report.get("passed") is True, report.get("passed"), True),
        (
            "sliceStart",
            float(report.get("sliceStart") or 0.0) == float(baseline["sliceStart"]),
            report.get("sliceStart"),
            baseline["sliceStart"],
        ),
        (
            "sliceDuration",
            float(report.get("sliceDuration") or 0.0) >= float(baseline["sliceDuration"]),
            report.get("sliceDuration"),
            f">= {baseline['sliceDuration']}",
        ),
        (
            "eventCount",
            int(report.get("eventCount") or 0) >= int(baseline["minimumEventCount"]),
            report.get("eventCount"),
            f">= {baseline['minimumEventCount']}",
        ),
        (
            "harmonicWindowCount",
            int(report.get("harmonicWindowCount") or 0) >= int(baseline["minimumHarmonicWindowCount"]),
            report.get("harmonicWindowCount"),
            f">= {baseline['minimumHarmonicWindowCount']}",
        ),
        (
            "chordWindowCount",
            int(report.get("chordWindowCount") or 0) >= int(baseline["minimumChordWindowCount"]),
            report.get("chordWindowCount"),
            f">= {baseline['minimumChordWindowCount']}",
        ),
        (
            "matchedChordWindowCount",
            int(report.get("matchedChordWindowCount") or 0) >= int(baseline["minimumMatchedChordWindowCount"]),
            report.get("matchedChordWindowCount"),
            f">= {baseline['minimumMatchedChordWindowCount']}",
        ),
        (
            "collapsedChordCount",
            int(report.get("collapsedChordCount") or 0) >= int(baseline["minimumCollapsedChordCount"]),
            report.get("collapsedChordCount"),
            f">= {baseline['minimumCollapsedChordCount']}",
        ),
        (
            "sustainedChordCount",
            int(report.get("sustainedChordCount") or 0) >= int(baseline["minimumSustainedChordCount"]),
            report.get("sustainedChordCount"),
            f">= {baseline['minimumSustainedChordCount']}",
        ),
        (
            "protectedBaselinesChanged",
            report.get("protectedBaselinesChanged") is baseline["protectedBaselinesChanged"],
            report.get("protectedBaselinesChanged"),
            baseline["protectedBaselinesChanged"],
        ),
    ]

    for chord in baseline["requiredChordVocabulary"]:
        checks.append(
            (
                f"chordVocabulary.{chord}",
                chord in vocabulary,
                chord in vocabulary,
                True,
            )
        )

    for chord, minimum in baseline["minimumRepeatedAttackCounts"].items():
        actual = int(repeated.get(chord) or 0)
        checks.append(
            (
                f"repeatedAttackCounts.{chord}",
                actual >= int(minimum),
                actual,
                f">= {minimum}",
            )
        )

    for name in baseline["requiredChecks"]:
        checks.append(
            (
                f"check.{name}",
                checks_map.get(name) is True,
                checks_map.get(name),
                True,
            )
        )

    print("JIMMY PAIGE GO MY WAY CHORUS CHORD & SUSTAIN REGRESSION GUARD")
    print("=" * 74)
    print("Analysis path:", report.get("analysisPath"))

    failed = False
    for name, passed, actual, expected in checks:
        marker = "PASS" if passed else "FAIL"
        print(f"{marker:4}  {name}: {actual}  expected {expected}")
        failed = failed or not passed

    if failed:
        raise SystemExit(
            "\nGo My Way chorus chord/sustain regression detected. "
            "Do not deploy this analyzer."
        )

    print("\nGO MY WAY CHORUS CHORD & SUSTAIN BASELINE PRESERVED 💚")


if __name__ == "__main__":
    main()
