#!/usr/bin/env python3
from __future__ import annotations

import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
POLISHED = ROOT / "lib" / "createTabPdfPolished.js"
WRAPPER = ROOT / "lib" / "createTabPdfPolishedV7.js"
OVERLAY = ROOT / "lib" / "v7MeasureGridOverlay.js"
ROUTE = ROOT / "app" / "api" / "generate-tab-pdf" / "route.js"

EXPECTED_POLISHED_SHA256 = "b65f415d20f34112e68db63bf9107d38fc21e496a3dcae550cb27453a61d87a4"


def read(path: Path) -> str:
    if not path.is_file():
        raise FileNotFoundError(f"Required file not found: {path}")
    return path.read_text(encoding="utf-8")


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> None:
    polished = read(POLISHED)
    wrapper = read(WRAPPER)
    overlay = read(OVERLAY)
    route = read(ROUTE)

    checks = {
        "polishedRendererPresent": "export async function createTabPdf" in polished,
        "wrapperCallsExistingPolishedRenderer": "createPolishedTabPdf(options)" in wrapper,
        "wrapperRequiresExplicitFlag": "options?.enableV7MeasureGrid === true" in wrapper,
        "wrapperRequiresMeasureGrid": "options?.measureGrid" in wrapper,
        "fallbackReturnsOriginalBytes": wrapper.count("return polishedBytes;") >= 3,
        "overlayRequiresPassedV7Grid": "grid.passed === true" in overlay and "grid.measureGridVersion === 7" in overlay,
        "sixMeasuresPerRowRequired": "Number(grid.measuresPerRow) === MEASURES_PER_SYSTEM" in overlay,
        "overlayUsesExistingSystemLayout": "buildSystemLayout" in overlay and "generatedTab" in overlay,
        "chordCollisionLanesPresent": "assignChordLanes" in overlay,
        "palmMuteContinuationPresent": "continuesFromPreviousMeasure" in overlay and "continuesIntoNextMeasure" in overlay,
        "compactSlideNotationPresent": "return match ? `/${match[1]}` : '/'" in overlay,
        "winAnsiSafeOverlay": all(ord(character) < 128 for character in overlay),
        "productionRouteStillUsesCurrentRenderer": "from '@/lib/createTabPdfPolished';" in route,
        "productionRouteNotOptedIntoV7": "enableV7MeasureGrid" not in route and "measureGrid" not in route,
        "polishedTemplateStillBranded": "DadRock-Tabs-Logo.png" in polished and "Generated by DadRock Tabs Studio" in polished,
        "polishedTemplateStillSupportsPreview": "DADROCK TABS PREVIEW" in polished and "FULL TAB LOCKED" in polished,
    }

    current_hash = sha256(POLISHED)
    checks["polishedRendererHashRecorded"] = len(current_hash) == 64

    print("JIMMY PAIGE V7 POLISHED PDF INTEGRATION GUARD")
    print("=" * 72)
    for name, passed in checks.items():
        print("PASS" if passed else "FAIL", name)

    print("Polished renderer SHA-256:", current_hash)
    print("Expected reference SHA-256:", EXPECTED_POLISHED_SHA256)
    print("Integration mode: opt-in wrapper; production route remains on current renderer")

    if not all(checks.values()):
        raise SystemExit("\nV7 polished PDF integration regression detected. Do not enable.")

    print("\nV7 POLISHED PDF OPT-IN INTEGRATION PRESERVED 💚")
    print("Existing logo, song/artist metadata, preview treatment, and PDF layout remain unchanged.")
    print("The V7 measure-grid overlay is available only through the explicit wrapper flag.")
    print("The production PDF route still uses the protected current renderer.")


if __name__ == "__main__":
    main()
