#!/usr/bin/env python3
"""Create a reference-blind GitHub preregistration attestation payload.

The payload is intended to be generated by a read-only GitHub Actions run before
any purpose-built capture. It binds the exact content-only capture plan and its
machine-readable preregistration evidence to the Actions run identity/head SHA.
A later server-proof verifier must independently fetch GitHub's run metadata and
confirm the platform-reported run time predates every declared capture.

This script never opens audio/MIDI, runs Basic Pitch/V6, or inspects correctness.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import os
from pathlib import Path
from typing import Any

HERE = Path(__file__).resolve().parent
BINDING_PATH = HERE / "purpose_built_capture_preregistration_binding_v1.py"
spec = importlib.util.spec_from_file_location(
    "purpose_built_capture_preregistration_binding_v1", BINDING_PATH
)
assert spec and spec.loader
binding = importlib.util.module_from_spec(spec)
spec.loader.exec_module(binding)
base = binding.base

ATTESTATION_CONTRACT = "songsterr-fresh-purpose-built-preregistration-attestation-v1"
EVIDENCE_CONTRACT = "songsterr-fresh-purpose-built-preregistration-evidence-v1"
ATTESTATION_MODES = {"synthetic_ci", "real_preregistration"}
SYNTHETIC_FIXTURE_PREFIX = "scripts/songsterr-fresh/fixtures/"


def build_attestation(
    plan: Any,
    evidence: Any,
    *,
    plan_repo_path: str,
    repository: str,
    head_sha: str,
    run_id: str,
    run_attempt: str,
    workflow_ref: str,
    mode: str,
) -> dict[str, Any]:
    errors: list[str] = []
    plan_errors, planned_slots, reasons, criteria_bound = binding._validate_plan(plan)
    errors.extend(plan_errors)

    plan_sha = None
    if isinstance(plan, dict):
        plan_sha = base.sha256_bytes(base.canonical_json(plan).encode("utf-8"))

    if mode not in ATTESTATION_MODES:
        errors.append(f"ATTESTATION_MODE_INVALID:{mode!r}")
    if mode == "real_preregistration":
        if plan_repo_path.startswith(SYNTHETIC_FIXTURE_PREFIX):
            errors.append("REAL_PREREGISTRATION_CANNOT_USE_SYNTHETIC_PLAN_FIXTURE")
        if isinstance(plan, dict) and str(plan.get("planId", "")).lower().startswith("synthetic"):
            errors.append("REAL_PREREGISTRATION_CANNOT_USE_SYNTHETIC_PLAN_ID")

    if not isinstance(evidence, dict):
        errors.append("PREREGISTRATION_EVIDENCE_OBJECT_REQUIRED")
    else:
        if evidence.get("contract") != EVIDENCE_CONTRACT:
            errors.append(
                "PREREGISTRATION_EVIDENCE_CONTRACT_MISMATCH:"
                f"{evidence.get('contract')!r}"
            )
        if evidence.get("capturePlanPath") != plan_repo_path:
            errors.append("PREREGISTRATION_EVIDENCE_PLAN_PATH_MISMATCH")
        if evidence.get("capturePlanSha256") != plan_sha:
            errors.append("PREREGISTRATION_EVIDENCE_PLAN_SHA256_MISMATCH")
        evidence_plan_path = evidence.get("capturePlanPath")
        if mode == "real_preregistration" and isinstance(evidence_plan_path, str):
            if evidence_plan_path.startswith(SYNTHETIC_FIXTURE_PREFIX):
                errors.append("REAL_PREREGISTRATION_CANNOT_USE_SYNTHETIC_EVIDENCE_BINDING")

    if not isinstance(repository, str) or "/" not in repository:
        errors.append("GITHUB_REPOSITORY_INVALID")
    if not base._is_commit(head_sha):
        errors.append("GITHUB_HEAD_SHA_INVALID")
    if not isinstance(run_id, str) or not run_id.isdigit():
        errors.append("GITHUB_RUN_ID_INVALID")
    if not isinstance(run_attempt, str) or not run_attempt.isdigit():
        errors.append("GITHUB_RUN_ATTEMPT_INVALID")
    if not isinstance(workflow_ref, str) or not workflow_ref.strip():
        errors.append("GITHUB_WORKFLOW_REF_REQUIRED")

    valid = not errors
    return {
        "contract": ATTESTATION_CONTRACT,
        "attestationValid": valid,
        "errors": sorted(set(errors)),
        "mode": mode,
        "repository": repository,
        "headSha": head_sha,
        "runId": run_id,
        "runAttempt": run_attempt,
        "workflowRef": workflow_ref,
        "capturePlanPath": plan_repo_path,
        "capturePlanSha256": plan_sha,
        "plannedSlotCount": len(planned_slots),
        "allowedAcquisitionFailureReasons": reasons,
        "failureCriteriaBound": criteria_bound and bool(reasons),
        "authoritativeStructuralSuitabilityEstablished": False,
        "basicPitchAuthorized": False,
        "v6Authorized": False,
        "correctnessAuthorized": False,
        "policyBoundary": dict(base.REQUIRED_POLICY_BOUNDARY),
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--capture-plan", required=True)
    parser.add_argument("--capture-plan-repo-path", required=True)
    parser.add_argument("--preregistration-evidence", required=True)
    parser.add_argument("--mode", required=True, choices=sorted(ATTESTATION_MODES))
    parser.add_argument("--output", required=True)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    plan = json.loads(Path(args.capture_plan).read_text(encoding="utf-8"))
    evidence = json.loads(Path(args.preregistration_evidence).read_text(encoding="utf-8"))
    result = build_attestation(
        plan,
        evidence,
        plan_repo_path=args.capture_plan_repo_path,
        repository=os.environ.get("GITHUB_REPOSITORY", ""),
        head_sha=os.environ.get("GITHUB_SHA", ""),
        run_id=os.environ.get("GITHUB_RUN_ID", ""),
        run_attempt=os.environ.get("GITHUB_RUN_ATTEMPT", ""),
        workflow_ref=os.environ.get("GITHUB_WORKFLOW_REF", ""),
        mode=args.mode,
    )
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(base.canonical_json(result) + "\n", encoding="utf-8")
    print(base.canonical_json(result))
    if result["attestationValid"]:
        print("PURPOSE_BUILT_PREREGISTRATION_ATTESTATION_V1_OK")
        return 0
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
