#!/usr/bin/env python3
"""Prospectively frozen synthetic gate suite for V3 iteration 3.

The 31 iteration-2 fixtures are generated by the frozen iteration-2 harness
without editing it. Its evaluator dependency is replaced in memory with a
minimal adapter to the iteration-3 wrapper, so fixture construction remains
byte-for-byte sourced from the frozen harness while decisions exercise V3.
"""

from __future__ import annotations

import math

import physical_template_plausibility_v3 as base
import physical_template_plausibility_v3_iteration2 as iteration2
import physical_template_plausibility_v3_iteration3 as iteration3
import test_physical_template_plausibility_v3_iteration2 as frozen_suite

EXPECTED_FIXTURE_COUNT = 34
FROZEN_ITERATION2_UNEXPECTED_PASS_NAMES = {
    "two_harmonics_only",
    "single_peak_only",
    "broadband_noise",
    "nonharmonic_impulses",
    "clip_start_insufficient_support",
}


class _Iteration3Adapter:
    @staticmethod
    def evaluate_owner_aware_composite(selected_midi, innovation, frequencies):
        return iteration3.evaluate_evidence_significance_composite(
            selected_midi,
            innovation,
            frequencies,
        )


def _install_frozen_fixture_adapter() -> None:
    # This mutates only the imported module object in memory. The frozen file is
    # never edited; all fixture builders and expected outcomes remain its code.
    frozen_suite.iteration2 = _Iteration3Adapter()


def build_new_scale_controls(records: list[dict]) -> None:
    low_valid = frozen_suite.fresh_spectrum(0.0002)
    frozen_suite.add_harmonic_series(
        low_valid,
        69,
        [0.100, 0.055, 0.036, 0.024, 0.017, 0.012],
    )
    records.append(
        frozen_suite.evaluate_case(
            "low_scale_valid_harmonic_a4",
            low_valid,
            69,
            True,
        )
    )

    low_noise = frozen_suite.fresh_spectrum(0.002)
    records.append(
        frozen_suite.evaluate_case(
            "low_scale_broadband_noise",
            low_noise,
            69,
            False,
        )
    )

    high_noise = frozen_suite.fresh_spectrum(0.20)
    records.append(
        frozen_suite.evaluate_case(
            "high_scale_broadband_noise",
            high_noise,
            69,
            False,
        )
    )


def collect_iteration3_mismatches(records: list[dict]) -> list[dict]:
    mismatches = list(frozen_suite.collect_mismatches(records))

    if len(records) != EXPECTED_FIXTURE_COUNT:
        mismatches.append(
            {
                "name": "__suite__",
                "reason": "FIXTURE_COUNT_MISMATCH",
                "expected": EXPECTED_FIXTURE_COUNT,
                "observed": len(records),
            }
        )

    if iteration3.CONTRACT != "songsterr-fresh-v3-physical-template-evidence-significance-synthetic-research-v3":
        mismatches.append({"name": "__contract__", "reason": "ITERATION3_CONTRACT_MISMATCH"})
    if iteration3.VERSION != 3:
        mismatches.append({"name": "__contract__", "reason": "ITERATION3_VERSION_MISMATCH"})
    if iteration3.MIN_CANDIDATE_EVIDENCE_FRACTION != 0.10:
        mismatches.append({"name": "__contract__", "reason": "ITERATION3_THRESHOLD_MISMATCH"})

    for record in records:
        if record.get("kind") != "composite":
            continue
        name = str(record.get("name"))
        actual = record.get("actual", {})
        if not isinstance(actual, dict):
            mismatches.append({"name": name, "reason": "ACTUAL_NOT_MAPPING"})
            continue

        iteration2_result = actual.get("iteration2Composite")
        if isinstance(iteration2_result, dict):
            if iteration2_result.get("passed") is not True and actual.get("passed") is True:
                mismatches.append({"name": name, "reason": "ILLEGAL_PROMOTION_OF_ITERATION2_FAILURE"})

        if actual.get("passed") is True:
            fraction = actual.get("candidateEvidenceFraction")
            if not isinstance(fraction, (int, float)) or not math.isfinite(float(fraction)):
                mismatches.append({"name": name, "reason": "PASS_WITHOUT_FINITE_EVIDENCE_FRACTION"})
            elif float(fraction) < iteration3.MIN_CANDIDATE_EVIDENCE_FRACTION:
                mismatches.append(
                    {
                        "name": name,
                        "reason": "PASS_BELOW_EVIDENCE_THRESHOLD",
                        "candidateEvidenceFraction": float(fraction),
                    }
                )

        if actual.get("status") == "INSUFFICIENT_CANDIDATE_EVIDENCE_SIGNIFICANCE":
            fraction = actual.get("candidateEvidenceFraction")
            if not isinstance(fraction, (int, float)) or not math.isfinite(float(fraction)):
                mismatches.append({"name": name, "reason": "SIGNIFICANCE_FAIL_WITHOUT_FINITE_FRACTION"})
            elif float(fraction) >= iteration3.MIN_CANDIDATE_EVIDENCE_FRACTION:
                mismatches.append(
                    {
                        "name": name,
                        "reason": "SIGNIFICANCE_FAIL_AT_OR_ABOVE_THRESHOLD",
                        "candidateEvidenceFraction": float(fraction),
                    }
                )

        if name in FROZEN_ITERATION2_UNEXPECTED_PASS_NAMES:
            if actual.get("passed") is True:
                mismatches.append({"name": name, "reason": "ITERATION2_SPURIOUS_PASS_NOT_REJECTED"})
            elif actual.get("status") != "INSUFFICIENT_CANDIDATE_EVIDENCE_SIGNIFICANCE":
                mismatches.append(
                    {
                        "name": name,
                        "reason": "SPURIOUS_PASS_NOT_REJECTED_BY_FROZEN_ITERATION3_GUARD",
                        "actualStatus": actual.get("status"),
                    }
                )

    return mismatches


def run_fixture_suite() -> dict:
    _install_frozen_fixture_adapter()

    frozen_report = frozen_suite.run_fixture_suite()
    records = list(frozen_report["fixtures"])
    if len(records) != 31:
        return {
            "contract": "songsterr-fresh-v3-physical-template-evidence-significance-synthetic-test-v3",
            "seed": frozen_suite.SEED,
            "fixtureCount": len(records),
            "mismatchCount": 1,
            "mismatches": [
                {
                    "name": "__suite__",
                    "reason": "FROZEN_ITERATION2_FIXTURE_COUNT_CHANGED",
                    "expected": 31,
                    "observed": len(records),
                }
            ],
            "fixtures": records,
        }

    build_new_scale_controls(records)
    mismatches = collect_iteration3_mismatches(records)
    return {
        "contract": "songsterr-fresh-v3-physical-template-evidence-significance-synthetic-test-v3",
        "seed": frozen_suite.SEED,
        "fixtureCount": len(records),
        "mismatchCount": len(mismatches),
        "mismatches": mismatches,
        "fixtures": records,
        "iteration2Contract": iteration2.CONTRACT,
        "iteration3Contract": iteration3.CONTRACT,
        "minimumCandidateEvidenceFraction": iteration3.MIN_CANDIDATE_EVIDENCE_FRACTION,
    }


def main() -> int:
    reports = [run_fixture_suite() for _ in range(3)]
    serializations = [frozen_suite.canonical_json(report) for report in reports]
    deterministic = bool(serializations[0] == serializations[1] == serializations[2])
    first = reports[0]
    passed = bool(deterministic and first["mismatchCount"] == 0)
    summary = {
        "contract": first["contract"],
        "fixtureCount": first["fixtureCount"],
        "mismatchCount": first["mismatchCount"],
        "mismatches": first["mismatches"],
        "repetitions": 3,
        "deterministic": deterministic,
        "result": "PASS" if passed else "FAIL",
    }
    print(frozen_suite.canonical_json(summary))
    return 0 if passed else 1


if __name__ == "__main__":
    raise SystemExit(main())
