#!/usr/bin/env python3
"""Fail fast when V72 adaptive separation activation regresses below the green baseline."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def load_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as file:
        return json.load(file)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--report",
        default="/tmp/v72-activation-report.json",
        help="Report generated by modal_analyzer_v72_activation_benchmark.py",
    )
    parser.add_argument(
        "--baseline",
        default="analyzer/baselines/v72_adaptive_activation_green.json",
        help="Frozen V72 adaptive activation baseline JSON",
    )
    args = parser.parse_args()

    report = load_json(Path(args.report))
    baseline = load_json(Path(args.baseline))

    checks: list[tuple[str, bool, Any, Any]] = [
        (
            "benchmarkType",
            report.get("benchmarkType") == baseline["benchmarkType"],
            report.get("benchmarkType"),
            baseline["benchmarkType"],
        ),
        (
            "engineVersion",
            report.get("engineVersion") == baseline["engineVersion"],
            report.get("engineVersion"),
            baseline["engineVersion"],
        ),
        (
            "passed",
            bool(report.get("passed")),
            report.get("passed"),
            True,
        ),
        (
            "stairwayMode",
            report.get("stairwayMode") == baseline["requiredStairwayMode"],
            report.get("stairwayMode"),
            baseline["requiredStairwayMode"],
        ),
        (
            "stairwayEventCount",
            int(report.get("stairwayEventCount") or 0)
            >= int(baseline["minimumStairwayEventCount"]),
            report.get("stairwayEventCount"),
            f">= {baseline['minimumStairwayEventCount']}",
        ),
    ]

    layered_modes = report.get("layeredModes") or {}
    layered_counts = report.get("layeredEventCounts") or {}

    for part, required_mode in baseline["requiredLayeredModes"].items():
        actual_mode = layered_modes.get(part)
        minimum_count = int(baseline["minimumLayeredEventCounts"][part])
        actual_count = int(layered_counts.get(part) or 0)
        checks.extend(
            [
                (
                    f"{part}.mode",
                    actual_mode == required_mode,
                    actual_mode,
                    required_mode,
                ),
                (
                    f"{part}.eventCount",
                    actual_count >= minimum_count,
                    actual_count,
                    f">= {minimum_count}",
                ),
            ]
        )

    report_checks = report.get("checks") or {}
    for check_name in baseline["requiredChecks"]:
        checks.append(
            (
                f"check.{check_name}",
                report_checks.get(check_name) is True,
                report_checks.get(check_name),
                True,
            )
        )

    failed = False
    print("JIMMY PAIGE V72 ADAPTIVE ACTIVATION REGRESSION GUARD")
    print("=" * 68)
    print("Engine:", report.get("engineVersion"))

    for name, passed, actual, expected in checks:
        marker = "PASS" if passed else "FAIL"
        print(f"{marker:4}  {name}: {actual}  expected {expected}")
        failed = failed or not passed

    if failed:
        raise SystemExit(
            "\nV72 adaptive activation regression detected. "
            "Do not deploy this analyzer."
        )

    print("\nV72 ADAPTIVE ACTIVATION BASELINE PRESERVED 💚")


if __name__ == "__main__":
    main()
