#!/usr/bin/env python3
"""Fail fast when the Go My Way 2 rhythm open-position benchmark regresses."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def load_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as file:
        return json.load(file)


def nested(data: dict[str, Any], *keys: str, default: Any = None) -> Any:
    value: Any = data
    for key in keys:
        if not isinstance(value, dict):
            return default
        value = value.get(key)
    return default if value is None else value


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--report",
        default="/tmp/gomyway2-rhythm-open-position-report.json",
        help="Report generated by modal_gomyway2_rhythm_open_position_benchmark.py",
    )
    parser.add_argument(
        "--baseline",
        default="analyzer/baselines/gomyway2_rhythm_open_position_green.json",
        help="Frozen rhythm open-position green baseline JSON",
    )
    args = parser.parse_args()

    report = load_json(Path(args.report))
    baseline = load_json(Path(args.baseline))
    after = report.get("after") or {}
    voicing = report.get("voicingDiagnostics") or {}
    technique = report.get("techniqueDiagnostics") or {}
    required_hits = after.get("requiredFretHits") or {}
    technique_checks = after.get("techniqueChecks") or {}

    checks: list[tuple[str, bool, Any, Any]] = [
        (
            "benchmarkVersion",
            int(report.get("benchmarkVersion") or 0) == int(baseline["benchmarkVersion"]),
            report.get("benchmarkVersion"),
            baseline["benchmarkVersion"],
        ),
        (
            "benchmarkType",
            report.get("benchmarkType") == baseline["benchmarkType"],
            report.get("benchmarkType"),
            baseline["benchmarkType"],
        ),
        (
            "engineVersion",
            report.get("engineVersion") == baseline["engineVersion"],
            report.get("engineVersion"),
            baseline["engineVersion"],
        ),
        (
            "instrumentSeparationMode",
            report.get("instrumentSeparationMode") == baseline["requiredMode"],
            report.get("instrumentSeparationMode"),
            baseline["requiredMode"],
        ),
        ("passed", report.get("passed") is True, report.get("passed"), True),
        (
            "after.comparisonScore",
            float(after.get("comparisonScore") or 0.0) >= float(baseline["minimumAfterScore"]),
            after.get("comparisonScore"),
            f">= {baseline['minimumAfterScore']}",
        ),
        (
            "scoreImprovement",
            float(report.get("scoreImprovement") or 0.0) >= float(baseline["minimumScoreImprovement"]),
            report.get("scoreImprovement"),
            f">= {baseline['minimumScoreImprovement']}",
        ),
        (
            "after.allowedFretPrecision",
            float(after.get("allowedFretPrecision") or 0.0) >= float(baseline["minimumAllowedFretPrecision"]),
            after.get("allowedFretPrecision"),
            f">= {baseline['minimumAllowedFretPrecision']}",
        ),
        (
            "after.requiredFretCoverage",
            float(after.get("requiredFretCoverage") or 0.0) >= float(baseline["minimumRequiredFretCoverage"]),
            after.get("requiredFretCoverage"),
            f">= {baseline['minimumRequiredFretCoverage']}",
        ),
        (
            "after.bestMotifScore",
            float(after.get("bestMotifScore") or 0.0) >= float(baseline["minimumBestMotifScore"]),
            after.get("bestMotifScore"),
            f">= {baseline['minimumBestMotifScore']}",
        ),
        (
            "voicing.exactCandidateCoverage",
            float(voicing.get("exactCandidateCoverage") or 0.0) >= float(baseline["minimumExactCandidateCoverage"]),
            voicing.get("exactCandidateCoverage"),
            f">= {baseline['minimumExactCandidateCoverage']}",
        ),
        (
            "technique.releasePairCount",
            int(technique.get("releasePairCount") or 0) >= int(baseline["minimumReleasePairCount"]),
            technique.get("releasePairCount"),
            f">= {baseline['minimumReleasePairCount']}",
        ),
        (
            "technique.syntheticNoteCount",
            int(technique.get("syntheticNoteCount") or 0) <= int(baseline["maximumSyntheticNoteCount"]),
            technique.get("syntheticNoteCount"),
            f"<= {baseline['maximumSyntheticNoteCount']}",
        ),
        (
            "protectedBaselinesChanged",
            report.get("protectedBaselinesChanged") is baseline["protectedBaselinesChanged"],
            report.get("protectedBaselinesChanged"),
            baseline["protectedBaselinesChanged"],
        ),
    ]

    for fret in baseline["requiredFrets"]:
        checks.append(
            (
                f"requiredFret.{fret}",
                required_hits.get(str(fret)) is True,
                required_hits.get(str(fret)),
                True,
            )
        )

    for name in baseline["requiredTechniques"]:
        checks.append(
            (
                f"technique.{name}",
                technique_checks.get(name) is True,
                technique_checks.get(name),
                True,
            )
        )

    print("JIMMY PAIGE GO MY WAY 2 RHYTHM OPEN-POSITION REGRESSION GUARD")
    print("=" * 72)
    print("Engine:", report.get("engineVersion"))

    failed = False
    for name, passed, actual, expected in checks:
        marker = "PASS" if passed else "FAIL"
        print(f"{marker:4}  {name}: {actual}  expected {expected}")
        failed = failed or not passed

    if failed:
        raise SystemExit(
            "\nGo My Way 2 rhythm open-position regression detected. "
            "Do not deploy this analyzer."
        )

    print("\nGO MY WAY 2 RHYTHM OPEN-POSITION BASELINE PRESERVED 💚")


if __name__ == "__main__":
    main()
