#!/usr/bin/env python3
"""Fail fast when the Go My Way 2 lead-technique handoff regresses."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def load_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as file:
        return json.load(file)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--report",
        default="/tmp/gomyway2-lead-technique-v3-report.json",
        help="Report generated by modal_gomyway2_lead_technique_handoff_benchmark_v3.py",
    )
    parser.add_argument(
        "--baseline",
        default="analyzer/baselines/gomyway2_lead_technique_v3_green.json",
        help="Frozen Go My Way 2 lead-technique green baseline JSON",
    )
    args = parser.parse_args()

    report = load_json(Path(args.report))
    baseline = load_json(Path(args.baseline))
    after = report.get("after") or {}
    techniques = after.get("techniqueChecks") or {}
    diagnostics = report.get("techniqueDiagnostics") or {}

    checks: list[tuple[str, bool, Any, Any]] = [
        (
            "benchmarkVersion",
            report.get("benchmarkVersion") == baseline["benchmarkVersion"],
            report.get("benchmarkVersion"),
            baseline["benchmarkVersion"],
        ),
        (
            "benchmarkType",
            report.get("benchmarkType") == baseline["benchmarkType"],
            report.get("benchmarkType"),
            baseline["benchmarkType"],
        ),
        (
            "engineVersion",
            report.get("engineVersion") == baseline["engineVersion"],
            report.get("engineVersion"),
            baseline["engineVersion"],
        ),
        (
            "instrumentSeparationMode",
            report.get("instrumentSeparationMode")
            == baseline["requiredInstrumentSeparationMode"],
            report.get("instrumentSeparationMode"),
            baseline["requiredInstrumentSeparationMode"],
        ),
        (
            "passed",
            bool(report.get("passed")),
            report.get("passed"),
            True,
        ),
        (
            "afterScore",
            float(after.get("comparisonScore") or 0.0)
            >= float(baseline["minimumAfterScore"]),
            after.get("comparisonScore"),
            f">= {baseline['minimumAfterScore']}",
        ),
        (
            "scoreImprovement",
            float(report.get("scoreImprovement") or 0.0)
            >= float(baseline["minimumScoreImprovement"]),
            report.get("scoreImprovement"),
            f">= {baseline['minimumScoreImprovement']}",
        ),
        (
            "releasePairCount",
            int(diagnostics.get("releasePairCount") or 0)
            >= int(baseline["minimumReleasePairCount"]),
            diagnostics.get("releasePairCount"),
            f">= {baseline['minimumReleasePairCount']}",
        ),
        (
            "palmMutedEventCount",
            int(diagnostics.get("palmMutedEventCount") or 0)
            >= int(baseline["minimumPalmMutedEventCount"]),
            diagnostics.get("palmMutedEventCount"),
            f">= {baseline['minimumPalmMutedEventCount']}",
        ),
        (
            "syntheticNoteCount",
            int(diagnostics.get("syntheticNoteCount") or 0)
            <= int(baseline["maximumSyntheticNoteCount"]),
            diagnostics.get("syntheticNoteCount"),
            f"<= {baseline['maximumSyntheticNoteCount']}",
        ),
        (
            "pitchOrFretChanged",
            bool(diagnostics.get("pitchOrFretChanged"))
            is bool(baseline["pitchOrFretChanged"]),
            diagnostics.get("pitchOrFretChanged"),
            baseline["pitchOrFretChanged"],
        ),
        (
            "requiredFretCoverage",
            float(after.get("requiredFretCoverage") or 0.0)
            >= float(baseline["requiredFretCoverage"]),
            after.get("requiredFretCoverage"),
            f">= {baseline['requiredFretCoverage']}",
        ),
        (
            "allowedFretPrecision",
            float(after.get("allowedFretPrecision") or 0.0)
            >= float(baseline["requiredAllowedFretPrecision"]),
            after.get("allowedFretPrecision"),
            f">= {baseline['requiredAllowedFretPrecision']}",
        ),
        (
            "protectedBaselinesChanged",
            bool(report.get("protectedBaselinesChanged"))
            is bool(baseline["protectedBaselinesChanged"]),
            report.get("protectedBaselinesChanged"),
            baseline["protectedBaselinesChanged"],
        ),
    ]

    for technique, required in baseline["requiredTechniqueChecks"].items():
        checks.append(
            (
                f"technique.{technique}",
                techniques.get(technique) is required,
                techniques.get(technique),
                required,
            )
        )

    failed = False
    print("JIMMY PAIGE GO MY WAY 2 LEAD-TECHNIQUE REGRESSION GUARD")
    print("=" * 68)
    print("Engine:", report.get("engineVersion"))

    for name, passed, actual, expected in checks:
        marker = "PASS" if passed else "FAIL"
        print(f"{marker:4}  {name}: {actual}  expected {expected}")
        failed = failed or not passed

    if failed:
        raise SystemExit(
            "\nGo My Way 2 lead-technique regression detected. "
            "Do not deploy this analyzer."
        )

    print("\nGO MY WAY 2 LEAD TECHNIQUE BASELINE PRESERVED 💚")


if __name__ == "__main__":
    main()
