#!/usr/bin/env python3
"""Fail fast when three-way instrument separation regresses below the green V5 baseline."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def load_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as file:
        return json.load(file)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--report",
        default="/tmp/gomyway2-instrument-v5-report.json",
        help="Report generated by modal_instrument_separation_benchmark_v5.py",
    )
    parser.add_argument(
        "--baseline",
        default="analyzer/baselines/gomyway2_three_way_separation_green.json",
        help="Frozen Go My Way 2 three-way separation baseline JSON",
    )
    args = parser.parse_args()

    report = load_json(Path(args.report))
    baseline = load_json(Path(args.baseline))

    checks: list[tuple[str, bool, Any, Any]] = [
        (
            "benchmarkVersion",
            int(report.get("benchmarkVersion") or 0)
            >= int(baseline["benchmarkVersion"]),
            report.get("benchmarkVersion"),
            f">= {baseline['benchmarkVersion']}",
        ),
        (
            "benchmarkType",
            report.get("benchmarkType") == baseline["benchmarkType"],
            report.get("benchmarkType"),
            baseline["benchmarkType"],
        ),
        (
            "protectedAnalyzer",
            report.get("protectedAnalyzer") == baseline["protectedAnalyzer"],
            report.get("protectedAnalyzer"),
            baseline["protectedAnalyzer"],
        ),
        (
            "policy",
            report.get("policy") == baseline["policy"],
            report.get("policy"),
            baseline["policy"],
        ),
        (
            "passed",
            bool(report.get("passed")),
            report.get("passed"),
            True,
        ),
    ]

    report_checks = report.get("checks") or {}
    separated = report.get("separatedSummaries") or {}

    for part, requirement in baseline["requiredParts"].items():
        part_check = report_checks.get(part) or {}
        part_summary = separated.get(part) or {}
        register_counts = part_summary.get("registerCounts") or {}

        observed = int(part_check.get("observedEventCount") or 0)
        expected_register_count = int(register_counts.get(part) or 0)
        contamination = float(part_check.get("contaminationRatio") or 0.0)
        minimum = int(requirement["minimumObservedEventCount"])
        maximum_contamination = float(requirement["maximumContaminationRatio"])

        checks.extend(
            [
                (
                    f"{part}.passed",
                    bool(part_check.get("passed")),
                    part_check.get("passed"),
                    True,
                ),
                (
                    f"{part}.observedEventCount",
                    observed >= minimum,
                    observed,
                    f">= {minimum}",
                ),
                (
                    f"{part}.registerCountMatches",
                    expected_register_count == observed,
                    expected_register_count,
                    observed,
                ),
                (
                    f"{part}.contaminationRatio",
                    contamination <= maximum_contamination,
                    contamination,
                    f"<= {maximum_contamination}",
                ),
            ]
        )

    failed = False
    print("JIMMY PAIGE GO MY WAY 2 INSTRUMENT-SEPARATION REGRESSION GUARD")
    print("=" * 68)
    print("Protected analyzer:", report.get("protectedAnalyzer"))

    for name, passed, actual, expected in checks:
        marker = "PASS" if passed else "FAIL"
        print(f"{marker:4}  {name}: {actual}  expected {expected}")
        failed = failed or not passed

    if failed:
        raise SystemExit(
            "\nThree-way instrument-separation regression detected. "
            "Do not deploy this analyzer."
        )

    print("\nGO MY WAY 2 THREE-WAY SEPARATION BASELINE PRESERVED 💚")


if __name__ == "__main__":
    main()
