import fs from 'node:fs/promises';
import path from 'node:path';
import {
  PDFDocument,
  StandardFonts,
  degrees,
  rgb,
} from 'pdf-lib';

const PAGE = {
  width: 612,
  height: 792,
  marginX: 46,
  contentRight: 566,
  footerY: 22,
  bottomLimit: 54,
};

const BRAND = {
  productTitle: 'DIY Guitar & Bass TAB Generator',
  logoFileName: 'DadRock-Tabs-Logo.png',
  previewWatermark: 'DADROCK TABS PREVIEW',
  previewLabel: 'PREVIEW ONLY',
  previewMessage: 'Unlock the complete unwatermarked tablature PDF below.',
  previewFooter: 'DadRock Tabs preview • dadrocktabs.com',
  finalFooter: 'Generated by DadRock Tabs • dadrocktabs.com',
};

const SECTION_PATTERN = /^(INTRO|VERSE(?:\s+\d+)?|PRE-CHORUS|CHORUS(?:\s+\d+)?|BRIDGE|SOLO|OUTRO|BREAKDOWN|INTERLUDE|RIFF|ENDING)\b/i;
const STRING_LINE_PATTERN = /^\s*([eEADGB])\s*\|?(.*)$/;
const TOKEN_PATTERN = /\d+(?:h|p|\/|\\|b|r)\d+|\d+~+|<\d+>|\(\d+\)|[xX]|\d+/g;
const SOURCE_MEASURES_PER_SYSTEM = 6;

function normalizeText(value) {
  return String(value || '')
    .replace(/\r\n/g, '\n')
    .replace(/\r/g, '\n');
}

function getStringLabels(transcriptionType) {
  return transcriptionType === 'bass'
    ? ['G', 'D', 'A', 'E']
    : ['e', 'B', 'G', 'D', 'A', 'E'];
}

function splitExplicitMeasures(content) {
  const source = String(content || '');
  const pieces = source.split('|').map((piece) => piece.trim());
  while (pieces.length && pieces[0] === '') pieces.shift();
  while (pieces.length && pieces.at(-1) === '') pieces.pop();
  return pieces;
}

function splitFixedMeasures(content, measureCount, sharedLength) {
  const source = String(content || '').padEnd(sharedLength, ' ');
  const measures = [];

  for (let index = 0; index < measureCount; index += 1) {
    const start = Math.round((index * sharedLength) / measureCount);
    const end = Math.round(((index + 1) * sharedLength) / measureCount);
    measures.push(source.slice(start, end).trim());
  }

  return measures;
}

function parseTabDocument(generatedTab, transcriptionType) {
  const expectedRows = transcriptionType === 'bass' ? 4 : 6;
  const labels = getStringLabels(transcriptionType);
  const blocks = [];
  let pendingSection = '';
  let currentRows = [];

  function flushRows() {
    if (currentRows.length !== expectedRows) {
      currentRows = [];
      return;
    }

    const hasExplicitBars = currentRows.some((row) => row.content.includes('|'));
    let rowMeasures;

    if (hasExplicitBars) {
      rowMeasures = currentRows.map((row) => splitExplicitMeasures(row.content));
    } else {
      const sharedLength = Math.max(
        ...currentRows.map((row) => String(row.content || '').length),
        SOURCE_MEASURES_PER_SYSTEM
      );
      rowMeasures = currentRows.map((row) =>
        splitFixedMeasures(
          row.content,
          SOURCE_MEASURES_PER_SYSTEM,
          sharedLength
        )
      );
    }

    const measureCount = Math.max(...rowMeasures.map((row) => row.length), 1);
    const measures = [];

    for (let measureIndex = 0; measureIndex < measureCount; measureIndex += 1) {
      measures.push(
        labels.map((label, stringIndex) => ({
          label,
          content: rowMeasures[stringIndex]?.[measureIndex] || '',
        }))
      );
    }

    blocks.push({ section: pendingSection, measures });
    pendingSection = '';
    currentRows = [];
  }

  for (const rawLine of normalizeText(generatedTab).split('\n')) {
    const line = rawLine.trimEnd();
    const trimmed = line.trim();

    if (SECTION_PATTERN.test(trimmed)) {
      flushRows();
      pendingSection = trimmed.replace(/[:\-]+$/, '').toUpperCase();
      continue;
    }

    const match = line.match(STRING_LINE_PATTERN);
    if (!match) {
      if (currentRows.length) flushRows();
      continue;
    }

    currentRows.push({ label: match[1], content: match[2] || '' });
    if (currentRows.length === expectedRows) flushRows();
  }

  flushRows();

  return blocks.length
    ? blocks
    : [{ section: '', measures: [labels.map((label) => ({ label, content: '' }))] }];
}

function createSystemRows(blocks, measuresPerRow) {
  const rows = [];
  let measureNumber = 1;

  for (const block of blocks) {
    for (let index = 0; index < block.measures.length; index += measuresPerRow) {
      const measures = block.measures.slice(index, index + measuresPerRow);
      rows.push({
        section: index === 0 ? block.section : '',
        measures,
        firstMeasureNumber: measureNumber,
      });
      measureNumber += measures.length;
    }
  }

  return rows;
}

function sanitizeTitle(value, fallback) {
  const cleaned = String(value || fallback).replace(/\s+/g, ' ').trim();
  return cleaned || fallback;
}

function extractTokens(content) {
  const source = String(content || '');
  return [...source.matchAll(TOKEN_PATTERN)].map((match) => ({
    text: match[0],
    index: match.index || 0,
  }));
}

function fitTextSize(font, text, maximumWidth, preferredSize, minimumSize = 8) {
  let size = preferredSize;
  while (size > minimumSize && font.widthOfTextAtSize(text, size) > maximumWidth) {
    size -= 0.5;
  }
  return size;
}

export async function createTabPdf({
  song,
  artist,
  transcriptionType,
  generatedTab,
  tuning = 'Standard Tuning',
  tempo = 120,
  timeSignature = '4/4',
  keySignature = '',
  preview = false,
  previewSystems = 4,
}) {
  const pdfDoc = await PDFDocument.create();
  const titleFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const bodyFont = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const tabFont = await pdfDoc.embedFont(StandardFonts.CourierBold);

  const logoPath = path.join(process.cwd(), 'public', BRAND.logoFileName);
  const logoBytes = await fs.readFile(logoPath);
  const logoImage = await pdfDoc.embedPng(logoBytes);
  const fullLogo = logoImage.scale(0.088);
  const compactLogo = logoImage.scale(0.046);

  const labels = getStringLabels(transcriptionType);
  const measuresPerRow = 4;
  const blocks = parseTabDocument(generatedTab, transcriptionType);
  const allRows = createSystemRows(blocks, measuresPerRow);
  const requestedPreviewRows = Math.max(1, Math.min(4, Number(previewSystems) || 4));
  const rows = preview ? allRows.slice(0, requestedPreviewRows) : allRows;

  const safeSong = sanitizeTitle(song, 'Untitled');
  const safeArtist = sanitizeTitle(artist, 'Unknown Artist');
  const safeInstrument = String(transcriptionType || 'lead').toUpperCase();
  const metadata = [
    String(tuning || 'Standard Tuning'),
    String(timeSignature || '4/4'),
    `${Number(tempo) || 120} BPM`,
  ];
  if (keySignature) metadata.push(String(keySignature));
  const settingsText = metadata.join(' • ');

  const stringSpacing = transcriptionType === 'bass' ? 11 : 9;
  const staffHeight = stringSpacing * (labels.length - 1);
  const rhythmAreaHeight = 14;
  const baseSystemHeight = staffHeight + rhythmAreaHeight + 20;
  const firstPageTop = 580;
  const continuationTop = 704;

  function drawHeader(page, compact = false) {
    if (compact) {
      page.drawImage(logoImage, {
        x: PAGE.marginX,
        y: 730,
        width: compactLogo.width,
        height: compactLogo.height,
      });

      const title = `${safeSong} — ${safeArtist}`;
      const titleX = PAGE.marginX + compactLogo.width + 10;
      const titleSize = fitTextSize(titleFont, title, 305, 11.5, 8.5);
      page.drawText(title, {
        x: titleX,
        y: 748,
        size: titleSize,
        font: titleFont,
        color: rgb(0.08, 0.08, 0.08),
      });
      page.drawText('CONTINUED', {
        x: titleX,
        y: 733,
        size: 7.5,
        font: bodyFont,
        color: rgb(0.55, 0.55, 0.55),
      });

      const settingsSize = fitTextSize(bodyFont, settingsText, 205, 7.5, 6.2);
      const settingsWidth = bodyFont.widthOfTextAtSize(settingsText, settingsSize);
      page.drawText(settingsText, {
        x: PAGE.contentRight - settingsWidth,
        y: 733,
        size: settingsSize,
        font: bodyFont,
        color: rgb(0.25, 0.25, 0.25),
      });

      page.drawLine({
        start: { x: PAGE.marginX, y: 720 },
        end: { x: PAGE.contentRight, y: 720 },
        thickness: 0.6,
        color: rgb(0.74, 0.74, 0.74),
      });
      return;
    }

    page.drawImage(logoImage, {
      x: (PAGE.width - fullLogo.width) / 2,
      y: 714,
      width: fullLogo.width,
      height: fullLogo.height,
    });

    const productSize = 15;
    const productWidth = titleFont.widthOfTextAtSize(BRAND.productTitle, productSize);
    page.drawText(BRAND.productTitle, {
      x: (PAGE.width - productWidth) / 2,
      y: 694,
      size: productSize,
      font: titleFont,
      color: rgb(1, 0.27, 0),
    });

    const songSize = fitTextSize(titleFont, safeSong, 500, 21, 14);
    page.drawText(safeSong, {
      x: PAGE.marginX,
      y: 656,
      size: songSize,
      font: titleFont,
      color: rgb(0.03, 0.03, 0.03),
    });

    const artistSize = fitTextSize(bodyFont, safeArtist, 360, 12.5, 9.5);
    page.drawText(safeArtist, {
      x: PAGE.marginX,
      y: 636,
      size: artistSize,
      font: bodyFont,
      color: rgb(0.38, 0.38, 0.38),
    });

    page.drawLine({
      start: { x: PAGE.marginX, y: 624 },
      end: { x: 215, y: 624 },
      thickness: 0.7,
      color: rgb(0.8, 0.8, 0.8),
    });

    page.drawText(safeInstrument, {
      x: PAGE.marginX,
      y: 603,
      size: 9.5,
      font: titleFont,
      color: rgb(0.12, 0.12, 0.12),
    });

    const settingsSize = fitTextSize(bodyFont, settingsText, 330, 8.5, 6.8);
    const settingsWidth = bodyFont.widthOfTextAtSize(settingsText, settingsSize);
    page.drawText(settingsText, {
      x: PAGE.contentRight - settingsWidth,
      y: 603,
      size: settingsSize,
      font: bodyFont,
      color: rgb(0.2, 0.2, 0.2),
    });
  }

  function drawMeasureContent({ page, content, x, width, stringY }) {
    const tokens = extractTokens(content);
    if (!tokens.length) return;

    const left = x + 12;
    const right = x + width - 12;
    const spread = Math.max(right - left, 12);

    tokens.forEach((token, index) => {
      const ratio = tokens.length === 1 ? 0.5 : index / (tokens.length - 1);
      const tokenX = left + ratio * spread;
      const size = token.text.length > 4 ? 7.2 : 8.2;
      const tokenWidth = tabFont.widthOfTextAtSize(token.text, size);

      page.drawRectangle({
        x: tokenX - tokenWidth / 2 - 1.5,
        y: stringY - 4.8,
        width: tokenWidth + 3,
        height: 11,
        color: rgb(1, 1, 1),
      });
      page.drawText(token.text, {
        x: tokenX - tokenWidth / 2,
        y: stringY - 3.3,
        size,
        font: tabFont,
        color: rgb(0.04, 0.04, 0.04),
      });
    });
  }

  function drawRhythmGuide(page, measureX, measureWidth, y) {
    const left = measureX + 10;
    const right = measureX + measureWidth - 10;
    page.drawLine({
      start: { x: left, y },
      end: { x: right, y },
      thickness: 0.55,
      color: rgb(0.58, 0.58, 0.58),
    });

    for (let beat = 0; beat <= 4; beat += 1) {
      const x = left + ((right - left) * beat) / 4;
      page.drawLine({
        start: { x, y },
        end: { x, y: y + 6 },
        thickness: 0.55,
        color: rgb(0.58, 0.58, 0.58),
      });
    }
  }

  function drawSystem(page, row, topY) {
    const sectionOffset = row.section ? 15 : 0;
    const staffTop = topY - sectionOffset;
    const measureCount = Math.max(row.measures.length, 1);
    const availableWidth = PAGE.contentRight - PAGE.marginX;
    const measureWidth = availableWidth / measureCount;

    if (row.section) {
      page.drawText(row.section, {
        x: PAGE.marginX,
        y: topY,
        size: 9,
        font: titleFont,
        color: rgb(0.92, 0.25, 0.02),
      });
      page.drawLine({
        start: { x: PAGE.marginX + 70, y: topY + 3 },
        end: { x: PAGE.contentRight, y: topY + 3 },
        thickness: 0.5,
        color: rgb(0.86, 0.86, 0.86),
      });
    }

    for (let measureIndex = 0; measureIndex < measureCount; measureIndex += 1) {
      const measureX = PAGE.marginX + measureIndex * measureWidth;
      page.drawText(String(row.firstMeasureNumber + measureIndex), {
        x: measureX + 3,
        y: staffTop + 9,
        size: 7,
        font: bodyFont,
        color: rgb(0.42, 0.42, 0.42),
      });
    }

    for (let stringIndex = 0; stringIndex < labels.length; stringIndex += 1) {
      const stringY = staffTop - stringIndex * stringSpacing;
      page.drawText(labels[stringIndex], {
        x: 32,
        y: stringY - 3.2,
        size: 7.5,
        font: titleFont,
        color: rgb(0.12, 0.12, 0.12),
      });

      page.drawLine({
        start: { x: PAGE.marginX, y: stringY },
        end: { x: PAGE.contentRight, y: stringY },
        thickness: 0.65,
        color: rgb(0.2, 0.2, 0.2),
      });

      for (let measureIndex = 0; measureIndex < measureCount; measureIndex += 1) {
        const measureX = PAGE.marginX + measureIndex * measureWidth;
        drawMeasureContent({
          page,
          content: row.measures[measureIndex]?.[stringIndex]?.content || '',
          x: measureX,
          width: measureWidth,
          stringY,
        });
      }
    }

    for (let divider = 0; divider <= measureCount; divider += 1) {
      const x = PAGE.marginX + divider * measureWidth;
      page.drawLine({
        start: { x, y: staffTop },
        end: { x, y: staffTop - staffHeight },
        thickness: divider === 0 || divider === measureCount ? 1 : 0.7,
        color: rgb(0.12, 0.12, 0.12),
      });
    }

    const rhythmY = staffTop - staffHeight - 13;
    for (let measureIndex = 0; measureIndex < measureCount; measureIndex += 1) {
      drawRhythmGuide(
        page,
        PAGE.marginX + measureIndex * measureWidth,
        measureWidth,
        rhythmY
      );
    }

    return baseSystemHeight + sectionOffset;
  }

  function addPreviewWatermark(page) {
    page.drawText(BRAND.previewWatermark, {
      x: 67,
      y: 335,
      size: 40,
      font: titleFont,
      color: rgb(0.7, 0.7, 0.7),
      rotate: degrees(34),
      opacity: 0.28,
    });

    page.drawRectangle({
      x: PAGE.marginX,
      y: 84,
      width: PAGE.contentRight - PAGE.marginX,
      height: 62,
      color: rgb(0.98, 0.95, 0.9),
      borderColor: rgb(1, 0.27, 0),
      borderWidth: 1.1,
    });
    page.drawText(BRAND.previewLabel, {
      x: PAGE.marginX + 18,
      y: 122,
      size: 10.5,
      font: titleFont,
      color: rgb(1, 0.27, 0),
    });
    page.drawText(BRAND.previewMessage, {
      x: PAGE.marginX + 18,
      y: 101,
      size: 8.5,
      font: titleFont,
      color: rgb(0.12, 0.12, 0.12),
    });
  }

  let rowIndex = 0;
  let page = pdfDoc.addPage([PAGE.width, PAGE.height]);
  drawHeader(page, false);
  let currentY = firstPageTop;

  while (rowIndex < rows.length) {
    const row = rows[rowIndex];
    const requiredHeight = baseSystemHeight + (row.section ? 15 : 0);

    if (currentY - requiredHeight < PAGE.bottomLimit) {
      page = pdfDoc.addPage([PAGE.width, PAGE.height]);
      drawHeader(page, true);
      currentY = continuationTop;
    }

    currentY -= drawSystem(page, row, currentY);
    rowIndex += 1;
  }

  if (preview) addPreviewWatermark(pdfDoc.getPages()[0]);

  const pages = pdfDoc.getPages();
  pages.forEach((pdfPage, index) => {
    const pageText = `Page ${index + 1} of ${pages.length}`;
    const pageTextSize = 8.5;
    const pageTextWidth = bodyFont.widthOfTextAtSize(pageText, pageTextSize);
    const pageTextX = (PAGE.width - pageTextWidth) / 2;

    pdfPage.drawLine({
      start: { x: PAGE.marginX, y: 28 },
      end: { x: pageTextX - 14, y: 28 },
      thickness: 0.45,
      color: rgb(0.42, 0.42, 0.42),
    });
    pdfPage.drawText(pageText, {
      x: pageTextX,
      y: PAGE.footerY,
      size: pageTextSize,
      font: bodyFont,
      color: rgb(0.25, 0.25, 0.25),
    });
    pdfPage.drawLine({
      start: { x: pageTextX + pageTextWidth + 14, y: 28 },
      end: { x: PAGE.contentRight, y: 28 },
      thickness: 0.45,
      color: rgb(0.42, 0.42, 0.42),
    });

    const footer = preview ? BRAND.previewFooter : BRAND.finalFooter;
    const footerSize = 6.5;
    const footerWidth = bodyFont.widthOfTextAtSize(footer, footerSize);
    pdfPage.drawText(footer, {
      x: (PAGE.width - footerWidth) / 2,
      y: 9,
      size: footerSize,
      font: bodyFont,
      color: rgb(0.45, 0.45, 0.45),
    });
  });

  return pdfDoc.save();
}
