import fs from 'node:fs/promises';
import path from 'node:path';
import {
  PDFDocument,
  StandardFonts,
  degrees,
  rgb,
} from 'pdf-lib';
import { createTabPdf as createBaseTabPdf } from '@/lib/createTabPdf';

const PAGE = {
  width: 612,
  height: 792,
  marginX: 50,
  contentRight: 560,
};

function cleanText(value, fallback) {
  const cleaned = String(value || fallback)
    .replace(/\s+/g, ' ')
    .trim();

  return cleaned || fallback;
}

function fitTextSize(font, text, maximumWidth, preferredSize, minimumSize = 8) {
  let size = preferredSize;

  while (
    size > minimumSize &&
    font.widthOfTextAtSize(text, size) > maximumWidth
  ) {
    size -= 0.5;
  }

  return size;
}

function drawCenteredText(page, text, y, size, font, color) {
  const width = font.widthOfTextAtSize(text, size);

  page.drawText(text, {
    x: (PAGE.width - width) / 2,
    y,
    size,
    font,
    color,
  });
}

export async function createTabPdf(options) {
  const baseBytes = await createBaseTabPdf(options);
  const pdfDoc = await PDFDocument.load(baseBytes);
  const pages = pdfDoc.getPages();

  if (!pages.length) {
    return baseBytes;
  }

  const titleFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const bodyFont = await pdfDoc.embedFont(StandardFonts.Helvetica);

  const logoPath = path.join(
    process.cwd(),
    'public',
    'DadRock-Tabs-Logo.png'
  );
  const logoBytes = await fs.readFile(logoPath);
  const logoImage = await pdfDoc.embedPng(logoBytes);
  const logo = logoImage.scaleToFit(170, 82);
  const logoTop = 778;
  const logoY = logoTop - logo.height;

  const song = cleanText(options?.song, 'Untitled');
  const artist = cleanText(options?.artist, 'Unknown Artist');
  const instrument = cleanText(
    options?.transcriptionType,
    'lead'
  ).toUpperCase();

  const metadata = [
    cleanText(options?.tuning, 'Standard Tuning'),
    cleanText(options?.timeSignature, '4/4'),
    `${Number(options?.tempo) || 120} BPM`,
  ];

  if (options?.keySignature) {
    metadata.push(cleanText(options.keySignature, ''));
  }

  const settingsText = metadata.filter(Boolean).join(' • ');
  const firstPage = pages[0];

  // Rebuild the first-page header with a safely bounded logo and the personal
  // DIY branding supported by a subtle DadRock AI credit.
  firstPage.drawRectangle({
    x: 0,
    y: 584,
    width: PAGE.width,
    height: PAGE.height - 584,
    color: rgb(1, 1, 1),
  });

  firstPage.drawImage(logoImage, {
    x: (PAGE.width - logo.width) / 2,
    y: logoY,
    width: logo.width,
    height: logo.height,
  });

  drawCenteredText(
    firstPage,
    'DIY Guitar & Bass TAB Generator',
    681,
    16,
    titleFont,
    rgb(1, 0.27, 0)
  );

  drawCenteredText(
    firstPage,
    'Powered by DadRock AI',
    667,
    8.5,
    bodyFont,
    rgb(0.42, 0.42, 0.42)
  );

  const songSize = fitTextSize(titleFont, song, 500, 20, 14);
  firstPage.drawText(song, {
    x: PAGE.marginX,
    y: 639,
    size: songSize,
    font: titleFont,
    color: rgb(0.03, 0.03, 0.03),
  });

  const artistSize = fitTextSize(bodyFont, artist, 360, 13, 9.5);
  firstPage.drawText(artist, {
    x: PAGE.marginX,
    y: 616,
    size: artistSize,
    font: bodyFont,
    color: rgb(0.38, 0.38, 0.38),
  });

  firstPage.drawLine({
    start: { x: PAGE.marginX, y: 604 },
    end: { x: 190, y: 604 },
    thickness: 0.8,
    color: rgb(0.82, 0.82, 0.82),
  });

  firstPage.drawText(instrument, {
    x: PAGE.marginX,
    y: 586,
    size: 10,
    font: titleFont,
    color: rgb(0.12, 0.12, 0.12),
  });

  const settingsSize = fitTextSize(
    bodyFont,
    settingsText,
    330,
    9,
    6.8
  );
  const settingsWidth = bodyFont.widthOfTextAtSize(
    settingsText,
    settingsSize
  );

  firstPage.drawText(settingsText, {
    x: PAGE.contentRight - settingsWidth,
    y: 586,
    size: settingsSize,
    font: bodyFont,
    color: rgb(0.2, 0.2, 0.2),
  });

  pages.forEach((page, index) => {
    // Replace the previous footer on both preview and unlocked PDFs.
    page.drawRectangle({
      x: 0,
      y: 0,
      width: PAGE.width,
      height: 18,
      color: rgb(1, 1, 1),
    });

    const footer = 'Generated by DadRock Tabs Studio • dadrocktabs.com';
    const footerSize = 6.5;
    const footerWidth = bodyFont.widthOfTextAtSize(
      footer,
      footerSize
    );

    page.drawText(footer, {
      x: (PAGE.width - footerWidth) / 2,
      y: 9,
      size: footerSize,
      font: bodyFont,
      color: rgb(0.45, 0.45, 0.45),
    });

    if (!options?.preview) {
      return;
    }

    // Strengthen the preview watermark without blocking the visible tab.
    page.drawText('DADROCK TABS PREVIEW', {
      x: 76,
      y: index === 0 ? 255 : 315,
      size: 38,
      font: titleFont,
      color: rgb(0.68, 0.68, 0.68),
      rotate: degrees(34),
      opacity: 0.13,
    });

    // Replace the original small lock notice with a taller value-focused box.
    page.drawRectangle({
      x: PAGE.marginX - 2,
      y: 40,
      width: PAGE.contentRight - PAGE.marginX + 4,
      height: 91,
      color: rgb(1, 1, 1),
    });

    page.drawRectangle({
      x: PAGE.marginX,
      y: 43,
      width: PAGE.contentRight - PAGE.marginX,
      height: 84,
      color: rgb(0.98, 0.95, 0.9),
      borderColor: rgb(1, 0.27, 0),
      borderWidth: 1.1,
      opacity: 0.98,
    });

    page.drawText('FULL TAB LOCKED', {
      x: PAGE.marginX + 18,
      y: 108,
      size: 10.5,
      font: titleFont,
      color: rgb(1, 0.27, 0),
    });

    page.drawText('Unlock your professional tablature PDF', {
      x: PAGE.marginX + 18,
      y: 92,
      size: 8.4,
      font: titleFont,
      color: rgb(0.12, 0.12, 0.12),
    });

    const benefits = [
      '• Complete transcription',
      '• Print-ready formatting',
      '• Instant download after purchase',
    ];

    benefits.forEach((benefit, benefitIndex) => {
      page.drawText(benefit, {
        x: PAGE.marginX + 18,
        y: 77 - benefitIndex * 11,
        size: 7.7,
        font: bodyFont,
        color: rgb(0.18, 0.18, 0.18),
      });
    });
  });

  return pdfDoc.save();
}
