import fs from 'node:fs/promises';
import path from 'node:path';
import {
  PDFDocument,
  StandardFonts,
  degrees,
  rgb,
} from 'pdf-lib';

const PAGE = {
  width: 612,
  height: 792,
  marginX: 50,
  contentRight: 560,
  footerY: 24,
  bottomLimit: 48,
};

const BRAND = {
  productTitle: 'DIY Guitar & Bass TAB Generator',
  logoFileName: 'DadRock-Tabs-Logo.png',
  previewWatermark: 'DADROCK TABS PREVIEW',
  previewLabel: 'PREVIEW ONLY',
  previewMessage: 'Unlock the complete unwatermarked tablature PDF below.',
  previewFooter: 'DadRock Tabs preview • dadrocktabs.com',
  finalFooter: 'Generated by DadRock Tabs • dadrocktabs.com',
};

const SECTION_PATTERN = /^(INTRO|VERSE(?:\s+\d+)?|PRE-CHORUS|CHORUS(?:\s+\d+)?|BRIDGE|SOLO|OUTRO|BREAKDOWN|INTERLUDE|RIFF|ENDING)\b/i;
const STRING_LINE_PATTERN = /^\s*([eEADGB])\s*\|?(.*)$/;
const TOKEN_PATTERN = /\d+(?:h|p|\/|\\|b|r)\d+|\d+~+|<\d+>|\(\d+\)|[xX]|\d+/g;
const MEASURES_PER_SYSTEM = 6;

function normalizeText(value) {
  return String(value || '')
    .replace(/\r\n/g, '\n')
    .replace(/\r/g, '\n');
}

function getStringLabels(transcriptionType) {
  return transcriptionType === 'bass'
    ? ['G', 'D', 'A', 'E']
    : ['e', 'B', 'G', 'D', 'A', 'E'];
}

function sanitizeTitle(value, fallback) {
  const cleaned = String(value || fallback)
    .replace(/\s+/g, ' ')
    .trim();
  return cleaned || fallback;
}

function parseTabSystems(generatedTab, transcriptionType) {
  const expectedRows = transcriptionType === 'bass' ? 4 : 6;
  const labels = getStringLabels(transcriptionType);
  const systems = [];
  let pendingSection = '';
  let currentRows = [];

  function flushRows() {
    if (currentRows.length !== expectedRows) {
      currentRows = [];
      return;
    }

    const sharedLength = Math.max(
      ...currentRows.map((row) => String(row.content || '').length),
      MEASURES_PER_SYSTEM
    );

    systems.push({
      section: pendingSection,
      rows: labels.map((label, index) => ({
        label,
        content: String(currentRows[index]?.content || '').padEnd(sharedLength, ' '),
      })),
      sourceLength: sharedLength,
    });

    pendingSection = '';
    currentRows = [];
  }

  for (const rawLine of normalizeText(generatedTab).split('\n')) {
    const line = rawLine.trimEnd();
    const trimmed = line.trim();

    if (SECTION_PATTERN.test(trimmed)) {
      flushRows();
      pendingSection = trimmed.replace(/[:\-]+$/, '').toUpperCase();
      continue;
    }

    const match = line.match(STRING_LINE_PATTERN);
    if (!match) {
      if (currentRows.length) flushRows();
      continue;
    }

    currentRows.push({
      label: match[1],
      content: match[2] || '',
    });

    if (currentRows.length === expectedRows) flushRows();
  }

  flushRows();

  if (!systems.length) {
    systems.push({
      section: '',
      rows: labels.map((label) => ({ label, content: '' })),
      sourceLength: MEASURES_PER_SYSTEM,
    });
  }

  return systems;
}

function extractTokens(content) {
  const source = String(content || '');
  return [...source.matchAll(TOKEN_PATTERN)].map((match) => ({
    text: match[0],
    index: match.index || 0,
  }));
}

function fitTextSize(font, text, maximumWidth, preferredSize, minimumSize = 8) {
  let size = preferredSize;
  while (
    size > minimumSize &&
    font.widthOfTextAtSize(text, size) > maximumWidth
  ) {
    size -= 0.5;
  }
  return size;
}

export async function createTabPdf({
  song,
  artist,
  transcriptionType,
  generatedTab,
  tuning = 'Standard Tuning',
  tempo = 120,
  timeSignature = '4/4',
  keySignature = '',
  preview = false,
  previewSystems = 4,
}) {
  const pdfDoc = await PDFDocument.create();
  const titleFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const bodyFont = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const tabFont = await pdfDoc.embedFont(StandardFonts.CourierBold);

  const logoPath = path.join(
    process.cwd(),
    'public',
    BRAND.logoFileName
  );
  const logoBytes = await fs.readFile(logoPath);
  const logoImage = await pdfDoc.embedPng(logoBytes);
  const fullLogo = logoImage.scale(0.095);
  const compactLogo = logoImage.scale(0.052);

  const labels = getStringLabels(transcriptionType);
  const allSystems = parseTabSystems(generatedTab, transcriptionType);
  const previewCount = Math.max(
    1,
    Math.min(4, Number(previewSystems) || 4)
  );
  const systems = preview
    ? allSystems.slice(0, previewCount)
    : allSystems;

  const safeSong = sanitizeTitle(song, 'Untitled');
  const safeArtist = sanitizeTitle(artist, 'Unknown Artist');
  const safeInstrument = String(
    transcriptionType || 'lead'
  ).toUpperCase();

  const metadata = [
    String(tuning || 'Standard Tuning'),
    String(timeSignature || '4/4'),
    `${Number(tempo) || 120} BPM`,
  ];
  if (keySignature) metadata.push(String(keySignature));
  const settingsText = metadata.join(' • ');

  const stringSpacing = transcriptionType === 'bass' ? 9 : 7;
  const staffHeight = stringSpacing * (labels.length - 1);
  const baseSystemHeight = transcriptionType === 'bass' ? 59 : 58;
  const firstPageTop = 570;
  const continuationTop = 690;
  const measureWidth =
    (PAGE.contentRight - PAGE.marginX) / MEASURES_PER_SYSTEM;

  function drawHeader(page, compact = false) {
    if (compact) {
      page.drawImage(logoImage, {
        x: PAGE.marginX,
        y: 724,
        width: compactLogo.width,
        height: compactLogo.height,
      });

      const title = `${safeSong} — ${safeArtist}`;
      const titleX = PAGE.marginX + compactLogo.width + 10;
      const titleSize = fitTextSize(titleFont, title, 315, 11.5, 8.5);
      page.drawText(title, {
        x: titleX,
        y: 744,
        size: titleSize,
        font: titleFont,
        color: rgb(0.08, 0.08, 0.08),
      });

      page.drawText('CONTINUED', {
        x: titleX,
        y: 729,
        size: 7.5,
        font: bodyFont,
        color: rgb(0.55, 0.55, 0.55),
      });

      const settingsSize = fitTextSize(
        bodyFont,
        settingsText,
        205,
        7.5,
        6.2
      );
      const settingsWidth = bodyFont.widthOfTextAtSize(
        settingsText,
        settingsSize
      );
      page.drawText(settingsText, {
        x: PAGE.contentRight - settingsWidth,
        y: 729,
        size: settingsSize,
        font: bodyFont,
        color: rgb(0.25, 0.25, 0.25),
      });

      page.drawLine({
        start: { x: PAGE.marginX, y: 716 },
        end: { x: PAGE.contentRight, y: 716 },
        thickness: 0.6,
        color: rgb(0.74, 0.74, 0.74),
      });
      return;
    }

    page.drawImage(logoImage, {
      x: (PAGE.width - fullLogo.width) / 2,
      y: 708,
      width: fullLogo.width,
      height: fullLogo.height,
    });

    const productSize = 16;
    const productWidth = titleFont.widthOfTextAtSize(
      BRAND.productTitle,
      productSize
    );
    page.drawText(BRAND.productTitle, {
      x: (PAGE.width - productWidth) / 2,
      y: 690,
      size: productSize,
      font: titleFont,
      color: rgb(1, 0.27, 0),
    });

    const songSize = fitTextSize(titleFont, safeSong, 500, 20, 14);
    page.drawText(safeSong, {
      x: PAGE.marginX,
      y: 660,
      size: songSize,
      font: titleFont,
      color: rgb(0.03, 0.03, 0.03),
    });

    const artistSize = fitTextSize(bodyFont, safeArtist, 360, 13, 9.5);
    page.drawText(safeArtist, {
      x: PAGE.marginX,
      y: 638,
      size: artistSize,
      font: bodyFont,
      color: rgb(0.38, 0.38, 0.38),
    });

    page.drawLine({
      start: { x: PAGE.marginX, y: 628 },
      end: { x: 190, y: 628 },
      thickness: 0.8,
      color: rgb(0.82, 0.82, 0.82),
    });

    page.drawText(safeInstrument, {
      x: PAGE.marginX,
      y: 606,
      size: 10,
      font: titleFont,
      color: rgb(0.12, 0.12, 0.12),
    });

    const settingsSize = fitTextSize(
      bodyFont,
      settingsText,
      330,
      9,
      6.8
    );
    const settingsWidth = bodyFont.widthOfTextAtSize(
      settingsText,
      settingsSize
    );
    page.drawText(settingsText, {
      x: PAGE.contentRight - settingsWidth,
      y: 606,
      size: settingsSize,
      font: bodyFont,
      color: rgb(0.2, 0.2, 0.2),
    });
  }

  function drawTokens(page, content, sourceLength, stringY) {
    const tokens = extractTokens(content);
    const usableWidth = PAGE.contentRight - PAGE.marginX - 10;
    const denominator = Math.max(sourceLength - 1, 1);

    for (const token of tokens) {
      const ratio = Math.min(1, token.index / denominator);
      const tokenX = PAGE.marginX + 5 + ratio * usableWidth;
      const size = token.text.length > 4 ? 7.1 : 7.8;
      const tokenWidth = tabFont.widthOfTextAtSize(token.text, size);

      page.drawRectangle({
        x: tokenX - 1.5,
        y: stringY - 4.5,
        width: tokenWidth + 3,
        height: 10,
        color: rgb(1, 1, 1),
      });

      page.drawText(token.text, {
        x: tokenX,
        y: stringY - 3,
        size,
        font: tabFont,
        color: rgb(0.04, 0.04, 0.04),
      });
    }
  }

  function drawSystem(page, system, topY, firstMeasureNumber) {
    const sectionOffset = system.section ? 15 : 0;
    const staffTop = topY - sectionOffset;

    if (system.section) {
      page.drawText(system.section, {
        x: PAGE.marginX,
        y: topY,
        size: 9,
        font: titleFont,
        color: rgb(0.92, 0.25, 0.02),
      });
      page.drawLine({
        start: { x: PAGE.marginX + 70, y: topY + 3 },
        end: { x: PAGE.contentRight, y: topY + 3 },
        thickness: 0.5,
        color: rgb(0.86, 0.86, 0.86),
      });
    }

    for (
      let measureIndex = 0;
      measureIndex < MEASURES_PER_SYSTEM;
      measureIndex += 1
    ) {
      page.drawText(String(firstMeasureNumber + measureIndex), {
        x: PAGE.marginX + measureIndex * measureWidth + 3,
        y: staffTop + 10,
        size: 7.5,
        font: bodyFont,
        color: rgb(0.42, 0.42, 0.42),
      });
    }

    for (let stringIndex = 0; stringIndex < labels.length; stringIndex += 1) {
      const stringY = staffTop - stringIndex * stringSpacing;
      const row = system.rows[stringIndex] || {
        label: labels[stringIndex],
        content: '',
      };

      page.drawText(labels[stringIndex], {
        x: 36,
        y: stringY - 3,
        size: 7,
        font: titleFont,
        color: rgb(0.12, 0.12, 0.12),
      });

      page.drawLine({
        start: { x: PAGE.marginX, y: stringY },
        end: { x: PAGE.contentRight, y: stringY },
        thickness: 0.7,
        color: rgb(0.16, 0.16, 0.16),
      });

      drawTokens(
        page,
        row.content,
        system.sourceLength,
        stringY
      );
    }

    for (
      let divider = 0;
      divider <= MEASURES_PER_SYSTEM;
      divider += 1
    ) {
      const x = PAGE.marginX + divider * measureWidth;
      page.drawLine({
        start: { x, y: staffTop },
        end: { x, y: staffTop - staffHeight },
        thickness:
          divider === 0 || divider === MEASURES_PER_SYSTEM
            ? 1
            : 0.7,
        color: rgb(0.12, 0.12, 0.12),
      });
    }

    return baseSystemHeight + sectionOffset;
  }

  function addPreviewWatermark(page) {
    page.drawText(BRAND.previewWatermark, {
      x: 67,
      y: 335,
      size: 40,
      font: titleFont,
      color: rgb(0.7, 0.7, 0.7),
      rotate: degrees(34),
      opacity: 0.28,
    });

    page.drawRectangle({
      x: PAGE.marginX,
      y: 84,
      width: PAGE.contentRight - PAGE.marginX,
      height: 62,
      color: rgb(0.98, 0.95, 0.9),
      borderColor: rgb(1, 0.27, 0),
      borderWidth: 1.1,
    });

    page.drawText(BRAND.previewLabel, {
      x: PAGE.marginX + 18,
      y: 122,
      size: 10.5,
      font: titleFont,
      color: rgb(1, 0.27, 0),
    });

    page.drawText(BRAND.previewMessage, {
      x: PAGE.marginX + 18,
      y: 101,
      size: 8.5,
      font: titleFont,
      color: rgb(0.12, 0.12, 0.12),
    });
  }

  let systemIndex = 0;
  let firstMeasureNumber = 1;
  let page = pdfDoc.addPage([PAGE.width, PAGE.height]);
  drawHeader(page, false);
  let currentY = firstPageTop;

  while (systemIndex < systems.length) {
    const system = systems[systemIndex];
    const requiredHeight =
      baseSystemHeight + (system.section ? 15 : 0);

    if (currentY - requiredHeight < PAGE.bottomLimit) {
      page = pdfDoc.addPage([PAGE.width, PAGE.height]);
      drawHeader(page, true);
      currentY = continuationTop;
    }

    currentY -= drawSystem(
      page,
      system,
      currentY,
      firstMeasureNumber
    );
    firstMeasureNumber += MEASURES_PER_SYSTEM;
    systemIndex += 1;
  }

  if (preview) addPreviewWatermark(pdfDoc.getPages()[0]);

  const pages = pdfDoc.getPages();
  pages.forEach((pdfPage, index) => {
    const pageText = `Page ${index + 1} of ${pages.length}`;
    const pageTextSize = 8.5;
    const pageTextWidth = bodyFont.widthOfTextAtSize(
      pageText,
      pageTextSize
    );
    const pageTextX = (PAGE.width - pageTextWidth) / 2;

    pdfPage.drawLine({
      start: { x: PAGE.marginX, y: 28 },
      end: { x: pageTextX - 14, y: 28 },
      thickness: 0.45,
      color: rgb(0.42, 0.42, 0.42),
    });

    pdfPage.drawText(pageText, {
      x: pageTextX,
      y: PAGE.footerY,
      size: pageTextSize,
      font: bodyFont,
      color: rgb(0.25, 0.25, 0.25),
    });

    pdfPage.drawLine({
      start: {
        x: pageTextX + pageTextWidth + 14,
        y: 28,
      },
      end: { x: PAGE.contentRight, y: 28 },
      thickness: 0.45,
      color: rgb(0.42, 0.42, 0.42),
    });

    const footer = preview
      ? BRAND.previewFooter
      : BRAND.finalFooter;
    const footerSize = 6.5;
    const footerWidth = bodyFont.widthOfTextAtSize(
      footer,
      footerSize
    );

    pdfPage.drawText(footer, {
      x: (PAGE.width - footerWidth) / 2,
      y: 9,
      size: footerSize,
      font: bodyFont,
      color: rgb(0.45, 0.45, 0.45),
    });
  });

  return pdfDoc.save();
}
