// Curated playlist/collection data for themed browse pages
// Each playlist targets specific user intents and long-tail keywords

export const PLAYLISTS = {
  'beginner-riffs-starter-pack': {
    name: 'Beginner Riffs Starter Pack',
    description: 'The 12 easiest and most rewarding guitar riffs to learn first. Master these and you\'ll have a solid foundation.',
    icon: '🌱',
    color: 'from-green-500 to-emerald-600',
    difficulty: 'Beginner',
    songs: [
      // These are artist slugs + song hints - we'll match them against the DB
      { artist: 'AC/DC', songHint: 'back in black' },
      { artist: 'AC/DC', songHint: 'highway to hell' },
      { artist: 'AC/DC', songHint: 'tnt' },
      { artist: 'Black Sabbath', songHint: 'iron man' },
      { artist: 'Black Sabbath', songHint: 'paranoid' },
      { artist: 'Deep Purple', songHint: 'smoke on the water' },
      { artist: 'Kiss', songHint: 'rock and roll' },
      { artist: 'Poison', songHint: 'nothin' },
      { artist: 'Twisted Sister', songHint: 'we\'re not gonna take it' },
      { artist: 'Def Leppard', songHint: 'pour some sugar' },
      { artist: 'Quiet Riot', songHint: 'cum on feel' },
      { artist: 'ZZ Top', songHint: 'la grange' },
    ],
  },
  'essential-80s-solos': {
    name: 'Essential 80s Guitar Solos',
    description: 'The solos that defined a decade. From Van Halen\'s tapping to Slash\'s melodic genius — learn the licks that made the 80s the golden age of guitar.',
    icon: '📼',
    color: 'from-fuchsia-500 to-pink-600',
    difficulty: 'Intermediate',
    songs: [
      { artist: 'Van Halen', songHint: 'eruption' },
      { artist: 'Van Halen', songHint: 'panama' },
      { artist: 'Van Halen', songHint: 'hot for teacher' },
      { artist: 'Guns N Roses', songHint: 'sweet child' },
      { artist: 'Guns N Roses', songHint: 'paradise city' },
      { artist: 'Def Leppard', songHint: 'photograph' },
      { artist: 'Scorpions', songHint: 'rock you like' },
      { artist: 'Whitesnake', songHint: 'still of the night' },
      { artist: 'Dokken', songHint: 'alone again' },
      { artist: 'Ozzy Osbourne', songHint: 'crazy train' },
    ],
  },
  'headbanger-classics': {
    name: 'Headbanger Classics',
    description: 'The heaviest, most aggressive riffs in rock. These songs will test your downpicking endurance and headbanging stamina.',
    icon: '🤘',
    color: 'from-red-600 to-rose-700',
    difficulty: 'Advanced',
    songs: [
      { artist: 'Metallica', songHint: 'master of puppets' },
      { artist: 'Metallica', songHint: 'battery' },
      { artist: 'Metallica', songHint: 'creeping death' },
      { artist: 'Slayer', songHint: 'raining blood' },
      { artist: 'Megadeth', songHint: 'holy wars' },
      { artist: 'Megadeth', songHint: 'tornado' },
      { artist: 'Pantera', songHint: 'walk' },
      { artist: 'Pantera', songHint: 'cowboys' },
      { artist: 'Anthrax', songHint: 'caught' },
      { artist: 'Testament', songHint: 'practice' },
    ],
  },
  'power-ballads': {
    name: 'Ultimate Power Ballads',
    description: 'Lighters up! The most emotional and beautiful rock ballads, perfect for learning dynamics, clean tone, and expressive playing.',
    icon: '🕯️',
    color: 'from-amber-500 to-orange-600',
    difficulty: 'Intermediate',
    songs: [
      { artist: 'Scorpions', songHint: 'still loving you' },
      { artist: 'Guns N Roses', songHint: 'november rain' },
      { artist: 'Metallica', songHint: 'nothing else matters' },
      { artist: 'Bon Jovi', songHint: 'wanted dead' },
      { artist: 'Whitesnake', songHint: 'is this love' },
      { artist: 'Def Leppard', songHint: 'bringin' },
      { artist: 'Skid Row', songHint: 'i remember' },
      { artist: 'Warrant', songHint: 'heaven' },
      { artist: 'Cinderella', songHint: 'don\'t know' },
      { artist: 'Firehouse', songHint: 'love of a lifetime' },
    ],
  },
  'riff-workout': {
    name: 'The Riff Workout',
    description: 'Build your rhythm guitar stamina with these iconic riffs. Arranged from moderate to intense — a complete picking-hand workout.',
    icon: '💪',
    color: 'from-blue-600 to-indigo-700',
    difficulty: 'Intermediate',
    songs: [
      { artist: 'AC/DC', songHint: 'thunderstruck' },
      { artist: 'Iron Maiden', songHint: 'the trooper' },
      { artist: 'Iron Maiden', songHint: 'aces high' },
      { artist: 'Judas Priest', songHint: 'breaking the law' },
      { artist: 'Judas Priest', songHint: 'painkiller' },
      { artist: 'Motorhead', songHint: 'ace of spades' },
      { artist: 'Metallica', songHint: 'seek and destroy' },
      { artist: 'Metallica', songHint: 'enter sandman' },
      { artist: 'Megadeth', songHint: 'symphony of destruction' },
      { artist: 'Pantera', songHint: 'domination' },
    ],
  },
  'blues-rock-essentials': {
    name: 'Blues Rock Essentials',
    description: 'Master the blues-rock foundation with these soulful riffs and licks. Learn bending, vibrato, and the pentatonic patterns that define rock guitar.',
    icon: '🎵',
    color: 'from-indigo-600 to-blue-700',
    difficulty: 'Intermediate',
    songs: [
      { artist: 'Stevie Ray Vaughan', songHint: 'pride' },
      { artist: 'Eric Clapton', songHint: 'layla' },
      { artist: 'Gary Moore', songHint: 'still got the blues' },
      { artist: 'ZZ Top', songHint: 'sharp dressed' },
      { artist: 'Cream', songHint: 'sunshine' },
      { artist: 'Jimi Hendrix', songHint: 'voodoo' },
      { artist: 'Led Zeppelin', songHint: 'whole lotta love' },
      { artist: 'Aerosmith', songHint: 'walk this way' },
      { artist: 'Santana', songHint: 'smooth' },
      { artist: 'Joe Bonamassa', songHint: 'sloe gin' },
    ],
  },
};

export function getAllPlaylists() {
  return Object.entries(PLAYLISTS).map(([slug, playlist]) => ({
    slug,
    ...playlist,
  }));
}
